server:
  port: 0
spring:
  application:
    name: user-service
#  zipkin:
#    base-url: http://localhost:9411
#    enabled: true
  redis:
    host: localhost
    port: 6379
  sleuth:
    sampler:
      probability: 1.0

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-mysql:3306/user_msa?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

greeting:
  message: Welcome to the Simple E-commerce.


# feignclient logging
logging:
  level:
    com.example.userservice.client: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: health, httptrace, info, metrics, prometheus



token:
  expiration_time: 86400000
  secret: user_token

permitUrls:
  all:
  get:
  post: /join
  delete:
  put:
  patch: